namespace: capi-webhook-system

namePrefix: capmaas-

commonLabels:
  control-plane: capmaas-controller-manager

bases:
- ../../config/crd
- ../../config/webhook
- ../../config/manager
- ../../config/certmanager

patchesStrategicMerge:
  - ../../config/default/manager_image_patch.yaml
  - ../../config/default/manager_pull_policy.yaml
  - ../../config/default/manager_webhook_patch.yaml
  - ../../config/default/webhookcainjection_patch.yaml

vars:
  # [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER' prefix.
  - name: CERTIFICATE_NAMESPACE # namespace of the certificate CR
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1alpha2
      name: serving-cert # this name should match the one in certificate.yaml
    fieldref:
      fieldpath: metadata.namespace
  - name: CERTIFICATE_NAME
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1alpha2
      name: serving-cert # this name should match the one in certificate.yaml
  - name: SERVICE_NAMESPACE # namespace of the service
    objref:
      kind: Service
      version: v1
      name: webhook-service
    fieldref:
      fieldpath: metadata.namespace
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: webhook-service



patchesJson6902:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: maasclusters.infrastructure.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: maasmachines.infrastructure.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: maasmachinetemplates.infrastructure.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
